`define ENABLE 1'b1
`define DISABLE 1'b0
`define VALID 1'b1
`define INVALID 1'b0

/* Definition with instructions */
`define ALU_OPERATOR_BUS 7:0
`define ALU_CATEGORY_BUS 2:0

`define CATEGORY_NOP 3'b000
`define CATEGORY_LOGIC 3'b001
`define CATEGORY_SHIFT 3'b010      // FIXME: defined by myself

`define OPERATOR_NOP 8'b00000000      // FIXME: defined by myself
`define OPERATOR_OR 8'b00100101       // FIXME: defined by myself
`define OPERATOR_AND 8'b00000001      // FIXME: defined by myself
`define OPERATOR_XOR 8'b00000010      // FIXME: defined by myself
`define OPERATOR_NOR 8'b00000011      // FIXME: defined by myself
`define OPERATOR_SLL 8'b00000100      // FIXME: defined by myself
`define OPERATOR_SRL 8'b00000101      // FIXME: defined by myself
`define OPERATOR_SRA 8'b00000110      // FIXME: defined by myself

`define INST_NOP_ID 6'b000000
`define INST_NOP_CATEGORY `CATEGORY_NOP
`define INST_NOP_OPERATOR `OPERATOR_NOP

`define INST_AND_ID 6'b100100
`define INST_AND_CATEGORY `CATEGORY_LOGIC
`define INST_AND_OPERATOR `OPERATOR_AND

`define INST_ANDI_ID 6'b001100
`define INST_ANDI_CATEGORY `CATEGORY_LOGIC
`define INST_ANDI_OPERATOR `OPERATOR_AND

`define INST_OR_ID 6'b100101
`define INST_OR_CATEGORY `CATEGORY_LOGIC
`define INST_OR_OPERATOR `OPERATOR_OR

`define INST_ORI_ID 6'b001101
`define INST_ORI_CATEGORY `CATEGORY_LOGIC
`define INST_ORI_OPERATOR `OPERATOR_OR

`define INST_XOR_ID 6'b100110
`define INST_XOR_CATEGORY `CATEGORY_LOGIC
`define INST_XOR_OPERATOR `OPERATOR_XOR

`define INST_XORI_ID 6'b001110
`define INST_XORI_CATEGORY `CATEGORY_LOGIC
`define INST_XORI_OPERATOR `OPERATOR_XOR

`define INST_NOR_ID 6'b100111
`define INST_NOR_CATEGORY `CATEGORY_LOGIC
`define INST_NOR_OPERATOR `OPERATOR_NOR

`define INST_LUI_ID 6'b001111
`define INST_LUI_CATEGORY `CATEGORY_LOGIC
`define INST_LUI_OPERATOR `OPERATOR_OR

`define INST_SLL_ID 6'b000000
`define INST_SLL_CATEGORY `CATEGORY_SHIFT
`define INST_SLL_OPERATOR `OPERATOR_SLL

`define INST_SLLV_ID 6'b000100
`define INST_SLLV_CATEGORY `CATEGORY_SHIFT
`define INST_SLLV_OPERATOR `OPERATOR_SLL

`define INST_SRL_ID 6'b000010
`define INST_SRL_CATEGORY `CATEGORY_SHIFT
`define INST_SRL_OPERATOR `OPERATOR_SRL

`define INST_SRLV_ID 6'b000110
`define INST_SRLV_CATEGORY `CATEGORY_SHIFT
`define INST_SRLV_OPERATOR `OPERATOR_SRL

`define INST_SRA_ID 6'b000011
`define INST_SRA_CATEGORY `CATEGORY_SHIFT
`define INST_SRA_OPERATOR `OPERATOR_SRA

`define INST_SRAV_ID 6'b000111
`define INST_SRAV_CATEGORY `CATEGORY_SHIFT
`define INST_SRAV_OPERATOR `OPERATOR_SRA

`define INST_SYNC_ID 6'b001111
`define INST_SYNC_CATEGORY `CATEGORY_NOP
`define INST_SYNC_OPERATOR `OPERATOR_NOP

`define INST_PREF_ID 6'b110011
`define INST_PREF_CATEGORY `CATEGORY_NOP
`define INST_PREF_OPERATOR `OPERATOR_NOP

`define INST_SPEC_ID 6'b000000

`define INST_ADDR_BUS 31:0
`define INST_DATA_BUS 31:0

/* Definition with ROM */
`define MEMO_NUM 128
`define MEMO_NUM_LOG 7

/* Definition with register file */
`define REGS_NUM 32
`define REGS_NUM_LOG 5
`define REGS_ADDR_BUS 4:0
`define REGS_DATA_BUS 31:0
`define REGS_SIZE 5
